var request = require('request');
request.get({ url: 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=22.279213,%2089.550946&rankby=distance&key=%20AIzaSyAn3XHK4etmU1Fa0oRMOye_lLmV1GSVANQ', time: true }, function (err, response) {
    console.log('The actual time elapsed:', response.elapsedTime);
});
request.get({ url: 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?pagetoken=CqQCFwEAAODQgAvs6wrFzqxpRvXaeDZT39SnBOI4EqMvu9DUD0ydql9uL2LXvKEgn5EoMqoMJPHFnwtELKexB-cUBQ_smNf7qKUBQ3bYOa8fbKjaOxWkls670YFu_IYkY_WBhKavA2wL5bycPdZkD7S7zsEscXD6o0PB0HR4oy2C-PCS9zjzhlxaSZhFrS01j_w10QCvw0YADFHbxhqi6wDKP7KJk6S9N6KOYRRHhfE8RFBSqsKTT0-hUO-UEjzhZ72127BIExcyjhKxr6SQyKeHDJted_M_OQEbxLSYPCXrl4jqEZWDmageaE_LQYVEK9U2W4h4GqZlDuJlM2ZYl91BqUXtMA97RKPkHzJGC2bMW0JcZScsRT_4B1Tw7tOeeOuOyV4HthIQrTxzzB81Bq_dZuJGlE6EORoUPrec-Jun-cfkvUfJQnj1qihuNnU&key=%20AIzaSyAn3XHK4etmU1Fa0oRMOye_lLmV1GSVANQ', time: true }, function (err, response) {
    console.log('The actual time elapsed:', response.elapsedTime);
});
request.get({ url: 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?pagetoken=CsQDtwEAAB6tc1xOMlRREbNLsStRDH7wbeiGznMQ9NWQITbYKMJuPtBv2lQj0ohHr2o9cpYWiyMkSginYcPL-DMvQoHoDRcTMroUKB6VJo0EWWlN6HkPQQ9bXqKOOjQTQClbhTHT8uTm-96NRtu93znM5UmtEgIq_LyfyW4oTwhHx8MX-ttuZg1vHugeJxHqVdS7rBFZAqtcfRUQvr7x1dKIxyYrvq-8h6yEPP62ZvqCqTe2rOBoqrdx6RH-uwsITWvSJuWdrP1KjVlKF5FBAmPu8IB1qzaXVvKZrUfkslrudZnYW81kZqHFa1IIZdZgMjkorj8fMcGFq32HxH2PwKVqjqVGHYVsjzJDdfu96R1LSdhiaqOI0nJE5msCwuh99-Xblgim0WSJX3idyuw6Hyh6M72DAI238OtwysXWkblDc_cccebhBnbC8uw42Y2uqnBgr_dUsGy0kcIrtr2mgmqx2l8--LaR-9F3CYzdG5gBwHMl__O_LyeABzen3TEAGByGzizRIUNohPxOxlphKWuA_aJ_HM0nb1k4F0_DL7mOxqtFnj6sBUxkOrzzpfYIJ1-fs_PebDgR9NwUeYSPuzkaVOpaZB4SEHBtYZY2sU90u2IukwrdXjUaFAuie-r6lWqqQp4Mql5SmT7Al6Fz&key=%20AIzaSyAn3XHK4etmU1Fa0oRMOye_lLmV1GSVANQ', time: true }, function (err, response) {
    console.log('The actual time elapsed:', response.elapsedTime);
});